### ISSUE TITLE
TensorFlow

### ISSUE THREAD

**Issue by mpmorley** [jlakkis/CarDEC#2]
Question does it really require such a specific version of Tenserflow? 

`
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.1 (from Cardec) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==2.0.1 (from Cardec)
`

**Comment by jlakkis** [comment]
Weird that it could not find the distribution for TF 2.0.1.

I tested the package with TF 2.3.1 (current release) and the code works fine with this TF distribution, so I have relaxed the CarDEC version requirement for TF. Now CarDEC will accept any version of TensorFlow >= 2.0.1, and <= 2.3.1. This range should capture the TF versions available according to your error message, and so should resolve the version issue. 

Marking this issue as closed.
